name: "Manik Rathee &#007C Designer"
description: "Design &amp; Development"
url: http://manikrathee.com/blog

#gems:        []
#timezone:    nil
#encoding:    nil

source: _prebuild/
permalink: /blog/posts/:year/:month/:day/:title.html

# include: [".htaccess"]
exclude: ['gruntfile.js', 'package.json', '/node_modules', '*.psd']
keep_files:  ['.git','.htaccess','.well-known']


safe: false
lsi: false
markdown: kramdown
highlighter: true

# sitemap:
#     file: "/sitemap.xml"
#     include_posts:
#         - "/index.html"
#     change_frequency_name: "change_frequency"
#     priority_name: "priority"

host:        127.0.0.1
port:        4000
